<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJfy8rdb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJfy8rdb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJfy8rdb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJfy8rdb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJfy8rdb\appProdProjectContainer([
    'container.build_hash' => 'Jfy8rdb',
    'container.build_id' => 'fd7fc821',
    'container.build_time' => 1574793666,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJfy8rdb');
